#! /usr/bin/env python
# -*- coding: utf-8 -*-
#
# @author      : {{+~g:name+}} ({{+~g:email+}})
# @file        : {{+~expand('%:t')+}}
# @created     : {{+~strftime("%c")+}}
# @description : {{++}}
#
# Distributed under terms of the {{+LICENSE+}} license.

"""
{{+ Description +}}
"""

# vim:fenc=utf-8
